/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'apps-branches-comparison': RouteRecordInfo<'apps-branches-comparison', '/apps/branches/comparison', Record<never, never>, Record<never, never>>,
    'apps-branches-list': RouteRecordInfo<'apps-branches-list', '/apps/branches/list', Record<never, never>, Record<never, never>>,
    'apps-employees-incentives': RouteRecordInfo<'apps-employees-incentives', '/apps/employees/incentives', Record<never, never>, Record<never, never>>,
    'apps-employees-list': RouteRecordInfo<'apps-employees-list', '/apps/employees/list', Record<never, never>, Record<never, never>>,
    'apps-employees-ranks': RouteRecordInfo<'apps-employees-ranks', '/apps/employees/ranks', Record<never, never>, Record<never, never>>,
    'apps-evaluations-list': RouteRecordInfo<'apps-evaluations-list', '/apps/evaluations/list', Record<never, never>, Record<never, never>>,
    'apps-insurance-forms-fire-theft': RouteRecordInfo<'apps-insurance-forms-fire-theft', '/apps/insurance-forms/fire-theft', Record<never, never>, Record<never, never>>,
    'apps-insurance-forms-life': RouteRecordInfo<'apps-insurance-forms-life', '/apps/insurance-forms/life', Record<never, never>, Record<never, never>>,
    'apps-policies-add': RouteRecordInfo<'apps-policies-add', '/apps/policies/add', Record<never, never>, Record<never, never>>,
    'apps-policies-expiring': RouteRecordInfo<'apps-policies-expiring', '/apps/policies/expiring', Record<never, never>, Record<never, never>>,
    'apps-policies-list': RouteRecordInfo<'apps-policies-list', '/apps/policies/list', Record<never, never>, Record<never, never>>,
    'apps-production-plans-id': RouteRecordInfo<'apps-production-plans-id', '/apps/production-plans/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-production-plans-add': RouteRecordInfo<'apps-production-plans-add', '/apps/production-plans/add', Record<never, never>, Record<never, never>>,
    'apps-production-plans-list': RouteRecordInfo<'apps-production-plans-list', '/apps/production-plans/list', Record<never, never>, Record<never, never>>,
    'apps-roles': RouteRecordInfo<'apps-roles', '/apps/roles', Record<never, never>, Record<never, never>>,
    'apps-settings-activity-logs': RouteRecordInfo<'apps-settings-activity-logs', '/apps/settings/activity-logs', Record<never, never>, Record<never, never>>,
    'apps-settings-branding': RouteRecordInfo<'apps-settings-branding', '/apps/settings/branding', Record<never, never>, Record<never, never>>,
    'apps-statistics-branches': RouteRecordInfo<'apps-statistics-branches', '/apps/statistics/branches', Record<never, never>, Record<never, never>>,
    'apps-statistics-employees': RouteRecordInfo<'apps-statistics-employees', '/apps/statistics/employees', Record<never, never>, Record<never, never>>,
    'apps-statistics-production': RouteRecordInfo<'apps-statistics-production', '/apps/statistics/production', Record<never, never>, Record<never, never>>,
    'apps-statistics-roi': RouteRecordInfo<'apps-statistics-roi', '/apps/statistics/roi', Record<never, never>, Record<never, never>>,
    'apps-user-list': RouteRecordInfo<'apps-user-list', '/apps/user/list', Record<never, never>, Record<never, never>>,
    'apps-user-view-id': RouteRecordInfo<'apps-user-view-id', '/apps/user/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'dashboards-insurance': RouteRecordInfo<'dashboards-insurance', '/dashboards/insurance', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
  }
}
